"""initial

Revision ID: 2b2e9327a6f7
Revises: 
Create Date: 2025-11-23 11:43:56.728554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '2b2e9327a6f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('locais')
    op.drop_table('user_permissions')
    op.drop_table('produtos')
    op.drop_table('historico_transferencias')
    op.drop_index(op.f('IX_admmat_UNE'), table_name='admmatao')
    op.drop_table('admmatao')
    op.drop_table('estoque')
    op.drop_table('usuarios')
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'ativo')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('ativo', mssql.BIT(), server_default=sa.text('((1))'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('role', sa.NVARCHAR(length=50, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('ativo', mssql.BIT(), server_default=sa.text('((1))'), autoincrement=False, nullable=True),
    sa.Column('tentativas_invalidas', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.Column('bloqueado_ate', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('ultimo_login', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('redefinir_solicitado', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.Column('redefinir_aprovado', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.Column('cloud_enabled', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.Column('segmento', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__usuarios__3213E83FC8894A8F')
    )
    op.create_table('estoque',
    sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('local_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('curva_une_30d', sa.VARCHAR(length=10, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('curva_cia_90d', sa.VARCHAR(length=10, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], name=op.f('FK__estoque__local_i__1BC821DD')),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('FK__estoque__produto__1CBC4616')),
    sa.PrimaryKeyConstraint('produto_id', 'local_id', name=op.f('PK__estoque__F140FDC8944F1481'))
    )
    op.create_table('admmatao',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('UNE', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('PRODUTO', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('TIPO', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('UNE_NOME', sa.NVARCHAR(length=53, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('NOME', sa.NVARCHAR(length=120, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('EMBALAGEM', sa.NVARCHAR(length=77, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('NOMESEGMENTO', sa.NVARCHAR(length=75, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('NOMECATEGORIA', sa.NVARCHAR(length=77, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('NOMEGRUPO', sa.NVARCHAR(length=85, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('NOMESUBGRUPO', sa.NVARCHAR(length=78, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('NOMEFABRICANTE', sa.NVARCHAR(length=90, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('EAN', sa.NVARCHAR(length=64, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PROMOCIONAL', sa.NVARCHAR(length=55, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('FORALINHA', sa.NVARCHAR(length=55, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LIQUIDO_38', sa.NVARCHAR(length=59, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('QTDE_EMB_MASTER', sa.NVARCHAR(length=60, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('QTDE_EMB_MULTIPLO', sa.NVARCHAR(length=59, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ABC_UNE_MES_04', sa.NVARCHAR(length=52, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ABC_UNE_MES_03', sa.NVARCHAR(length=52, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ABC_UNE_MES_02', sa.NVARCHAR(length=52, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ABC_UNE_MES_01', sa.NVARCHAR(length=52, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ABC_UNE_30DD', sa.NVARCHAR(length=52, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ABC_CACULA_90DD', sa.NVARCHAR(length=52, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ABC_UNE_30XABC_CACULA_90DD', sa.NVARCHAR(length=59, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MES_12', sa.NVARCHAR(length=59, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MES_11', sa.NVARCHAR(length=59, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MES_10', sa.NVARCHAR(length=59, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MES_09', sa.NVARCHAR(length=60, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MES_08', sa.NVARCHAR(length=59, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MES_07', sa.NVARCHAR(length=59, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MES_06', sa.NVARCHAR(length=59, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MES_05', sa.NVARCHAR(length=59, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MES_04', sa.NVARCHAR(length=59, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MES_03', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('MES_02', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('MES_01', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('MES_PARCIAL', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('SEMANA_ANTERIOR_5', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('FREQ_SEMANA_ANTERIOR_5', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('QTDE_SEMANA_ANTERIOR_5', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('MEDIA_SEMANA_ANTERIOR_5', sa.NVARCHAR(length=58, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SEMANA_ANTERIOR_4', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('FREQ_SEMANA_ANTERIOR_4', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('QTDE_SEMANA_ANTERIOR_4', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('MEDIA_SEMANA_ANTERIOR_4', sa.NVARCHAR(length=58, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SEMANA_ANTERIOR_3', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('FREQ_SEMANA_ANTERIOR_3', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('QTDE_SEMANA_ANTERIOR_3', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('MEDIA_SEMANA_ANTERIOR_3', sa.NVARCHAR(length=59, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SEMANA_ANTERIOR_2', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('FREQ_SEMANA_ANTERIOR_2', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('QTDE_SEMANA_ANTERIOR_2', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('MEDIA_SEMANA_ANTERIOR_2', sa.NVARCHAR(length=58, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SEMANA_ATUAL', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('FREQ_SEMANA_ATUAL', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('QTDE_SEMANA_ATUAL', sa.NVARCHAR(length=59, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MEDIA_SEMANA_ATUAL', sa.NVARCHAR(length=58, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('VENDA_30DD', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('MEDIA_CONSIDERADA_LV', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('ESTOQUE_CD', sa.NVARCHAR(length=74, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ULTIMA_ENTRADA_DATA_CD', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.Column('ULTIMA_ENTRADA_QTDE_CD', sa.NVARCHAR(length=73, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ULTIMA_ENTRADA_CUSTO_CD', sa.NVARCHAR(length=72, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ESTOQUE_UNE', sa.NVARCHAR(length=73, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ULTIMO_INVENTARIO_UNE', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.Column('ULTIMA_ENTRADA_DATA_UNE', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.Column('ULTIMA_ENTRADA_QTDE_UNE', sa.NVARCHAR(length=72, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ESTOQUE_LV', sa.NVARCHAR(length=71, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ESTOQUE_GONDOLA_LV', sa.NVARCHAR(length=71, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ESTOQUE_ILHA_LV', sa.NVARCHAR(length=70, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('EXPOSICAO_MINIMA', sa.NVARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('EXPOSICAO_MINIMA_UNE', sa.NVARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('EXPOSICAO_MAXIMA_UNE', sa.NVARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LEADTIME_LV', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('PONTO_PEDIDO_LV', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('MEDIA_TRAVADA', sa.NVARCHAR(length=55, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ENDERECO_RESERVA', sa.NVARCHAR(length=60, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ENDERECO_LINHA', sa.NVARCHAR(length=60, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SOLICITACAO_PENDENTE', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('SOLICITACAO_PENDENTE_DATA', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.Column('SOLICITACAO_PENDENTE_QTDE', sa.NVARCHAR(length=60, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SOLICITACAO_PENDENTE_SITUACAO', sa.NVARCHAR(length=51, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ULTIMA_VENDA_DATA_UNE', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.Column('PICKLIST', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('PICKLIST_SITUACAO', sa.NVARCHAR(length=52, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PICKLIST_CONFERENCIA', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.Column('ULTIMO_VOLUME', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('VOLUME_QTDE', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('ROMANEIO_SOLICITACAO', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('ROMANEIO_ENVIO', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('NOTA', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('SERIE', sa.NVARCHAR(length=54, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('NOTA_EMISSAO', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.Column('FREQ_ULT_SEM', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__admmatao__3213E83FBD150563'))
    )
    op.create_index(op.f('IX_admmat_UNE'), 'admmatao', ['UNE'], unique=False)
    op.create_table('historico_transferencias',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('local_origem_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('local_destino_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('solicitante_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['local_destino_id'], ['locais.id'], name=op.f('FK__historico__local__5224328E')),
    sa.ForeignKeyConstraint(['local_origem_id'], ['locais.id'], name=op.f('FK__historico__local__51300E55')),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('FK__historico__produ__503BEA1C')),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], name=op.f('FK__historico__solic__531856C7')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__historic__3213E83F123BDE4A'))
    )
    op.create_table('produtos',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=1000, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__produtos__3213E83F7B4D943A'))
    )
    op.create_table('user_permissions',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('page_file', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['username'], ['usuarios.username'], name=op.f('FK__user_perm__usern__7755B73D'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__user_per__3213E83F5FB5A532'))
    )
    op.create_table('locais',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__locais__3213E83F3C544D92'))
    )
    op.drop_table('reports')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
